// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxxejcxhkcmprptcdngk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eGVqY3hoa2NtcHJwdGNkbmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTU3ODIsImV4cCI6MjA2OTM5MTc4Mn0.6ibIEmcDIMvTBWjYMUBX7umvNpQP1jpnHAvT_wWM0a4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});